<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoomsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tbl_room')->insert([
        [    
            'room_number'=>'1',
            'room_type'=>'minimac',
            'status'=>'available',
            'price'=>120,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'2',
            'room_type'=>'minimac',
            'status'=>'available',
            'price'=>120,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'3',
            'room_type'=>'minimac',
            'status'=>'available',
            'price'=>120,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'4',
            'room_type'=>'minimac',
            'status'=>'available',
            'price'=>120,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'5',
            'room_type'=>'minimac',
            'status'=>'available',
            'price'=>120,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'6',
            'room_type'=>'minimac',
            'status'=>'available',
            'price'=>120,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'7',
            'room_type'=>'minimac',
            'status'=>'available',
            'price'=>120,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'8',
            'room_type'=>'minimac',
            'status'=>'available',
            'price'=>120,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'9',
            'room_type'=>'minimac',
            'status'=>'available',
            'price'=>120,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'10',
            'room_type'=>'minimac',
            'status'=>'available',
            'price'=>120,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'11',
            'room_type'=>'minimac',
            'status'=>'available',
            'price'=>120,
            'created_at'=>date_create()
        ],

        //standard
        [    
            'room_number'=>'12',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'13',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'14',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'15',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'16',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'17',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'18',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'19',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'20',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'21',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'22',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'23',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'24',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'25',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'26',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'27',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'28',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'29',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'30',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'31',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'32',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'33',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'34',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'35',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'36',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'37',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'38',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'39',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'40',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'41',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'42',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'43',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'44',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'45',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'46',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'47',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'48',
            'room_type'=>'standard',
            'status'=>'available',
            'price'=>160,
            'created_at'=>date_create()
        ],

        //deluxe
        [    
            'room_number'=>'49',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'50',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'51',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'52',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'53',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'54',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'55',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'56',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'57',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'58',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'59',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'60',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'61',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'62',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'63',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'64',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'65',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'66',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'67',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'68',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'69',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'70',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'71',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'72',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'73',
            'room_type'=>'deluxe',
            'status'=>'available',
            'price'=>180,
            'created_at'=>date_create()
        ],


        //premium
        [    
            'room_number'=>'74',
            'room_type'=>'premium',
            'status'=>'available',
            'price'=>200,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'75',
            'room_type'=>'premium',
            'status'=>'available',
            'price'=>200,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'76',
            'room_type'=>'premium',
            'status'=>'available',
            'price'=>200,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'77',
            'room_type'=>'premium',
            'status'=>'available',
            'price'=>200,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'78',
            'room_type'=>'premium',
            'status'=>'available',
            'price'=>200,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'79',
            'room_type'=>'premium',
            'status'=>'available',
            'price'=>200,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'80',
            'room_type'=>'premium',
            'status'=>'available',
            'price'=>200,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'81',
            'room_type'=>'premium',
            'status'=>'available',
            'price'=>200,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'82',
            'room_type'=>'premium',
            'status'=>'available',
            'price'=>200,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'83',
            'room_type'=>'premium',
            'status'=>'available',
            'price'=>200,
            'created_at'=>date_create()
        ],


        //family and suit
        [    
            'room_number'=>'84',
            'room_type'=>'family and suit',
            'status'=>'available',
            'price'=>280,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'85',
            'room_type'=>'family and suit',
            'status'=>'available',
            'price'=>280,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'86',
            'room_type'=>'family and suit',
            'status'=>'available',
            'price'=>280,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'87',
            'room_type'=>'family and suit',
            'status'=>'available',
            'price'=>280,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'88',
            'room_type'=>'family and suit',
            'status'=>'available',
            'price'=>280,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'89',
            'room_type'=>'family and suit',
            'status'=>'available',
            'price'=>280,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'90',
            'room_type'=>'family and suit',
            'status'=>'available',
            'price'=>280,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'91',
            'room_type'=>'family and suit',
            'status'=>'available',
            'price'=>280,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'92',
            'room_type'=>'family and suit',
            'status'=>'available',
            'price'=>280,
            'created_at'=>date_create()
        ],
        [    
            'room_number'=>'93',
            'room_type'=>'family and suit',
            'status'=>'available',
            'price'=>280,
            'created_at'=>date_create()
        ],


        //team
        [    
            'room_number'=>'94',
            'room_type'=>'team',
            'status'=>'available',
            'price'=>400,
            'created_at'=>date_create()
        ],
        ]);
    }
}
